spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/tradesman
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    liquibase: INFO


bucketname : tradesman-bucket
region : us-east-2